name: CI / CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: shifts_website

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.INSTANCE }}
          install_components: "beta" 

      - name: Configure Docker to use gcr.io
        run: gcloud auth configure-docker --quiet

      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: gcr.io/${{ secrets.INSTANCE }}/shift-scheduler:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy shift-scheduler \
            --image gcr.io/${{ secrets.INSTANCE }}/shift-scheduler:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars \
DB_USER=${{ secrets.DB_USER }},\
DB_PASS=${{ secrets.DB_PASS }},\
DB_NAME=${{ secrets.DB_NAME }},\
INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }},\
GOOGLE_ID=${{ secrets.GOOGLE_ID }},\
GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }},\
FLASK_KEY=${{ secrets.FLASK_KEY }}
